on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_ip }}
        username: ${{ secrets.ftp_name }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./public/*
        server-dir: ./htdocs/blog
